CREATE TABLE Advantage (
    Type_1  TEXT,
    Type_2  TEXT,
    Nor     INTEGER,
    Fig     INTEGER,
    Fly     INTEGER,
    Poi     INTEGER,
    Gro     INTEGER,
    Roc     INTEGER,
    Bug     INTEGER,
    Gho     INTEGER,
    Ste     INTEGER,
    Fir     INTEGER,
    Wat     INTEGER,
    Gra     INTEGER,
    Ele     INTEGER,
    Psy     INTEGER,
    Ice     INTEGER,
    Dra     INTEGER,
    Dar     INTEGER,
    Fai     INTEGER,
    PRIMARY KEY (Type_1, Type_2)
);