CREATE TABLE Pokemon (
    Kanto_id        INTEGER PRIMARY KEY,
    Name            TEXT,
    Entry           TEXT,
    Type_1          TEXT,
    Type_2          TEXT,
    Species         TEXT,
    Height          INTEGER,
    Weight          INTEGER,
    Ability_1       TEXT,
    Ability_2       TEXT,
    Hidden_ability  TEXT,
    Stat_id         INTEGER,
    Training_id     INTEGER,
    Breeding_id     INTEGER,
    Sprite_norm     TEXT,
    Sprite_shny     TEXT,
    FOREIGN KEY (Type_1) REFERENCES Advantage (Type_1),
    FOREIGN KEY (Type_2) REFERENCES Advantage (Type_2),
    FOREIGN KEY (Ability_1) REFERENCES Abilities (Name),
    FOREIGN KEY (Ability_2) REFERENCES Abilities (Name),
    FOREIGN KEY (Hidden_ability) REFERENCES Abilities (Name),
    FOREIGN KEY (Stat_id) REFERENCES Statistics (Stat_id),
    FOREIGN KEY (Training_id) REFERENCES Training (Training_id),
    FOREIGN KEY (Breeding_id) REFERENCES Breeding (Breeding_id)
);